Develop
umbrella-network/pegasus-feeds pull request #59
Opened 2022-01-05 15:19 UTC by jjordan-quantum

Created npm project and scripts for adding equity symbols to feeds.yaml (currently adds to feeds.yaml in /dev/bsc/ folder)

2022-01-07 20:03 UTC, dougmrqs requested changes

2022-01-07 20:03 UTC, dougmrqs commented on test/test.ts
> +  });
We usually use a framework like `chai` to assure everything works, but this use case would make a good example. Not sure about the time we want to spend on this task, but I think the goal is achieved. If we had more time, I'd recommend we implement a testing framework here.

Other than calling it a "test", we could call this an "example".

2022-01-07 20:03 UTC, dougmrqs commented on package.json
> +    "test": "tsc test/test.ts && cd test && node test.js"
Please mention this in the readme. Consider calling this script an example instead of a proper test.

2022-01-10 21:10 UTC, dougmrqs approved these changes
Looks good enough to me. Just some final hints to keep in mind: 
- We branch from the repository itself, not from a fork;
- We usually name our branches in the git/hubflow pattern, like "feature", "hotfix" and "release".
- We'll have to copy this script to the main branch, given our current strategy: develop branch serves feeds for develop and sandbox environment and main branch serves feeds for production environment.
- For this case, I'd name this branch a `feature/add-feeds-script`
- Should we update the feeds.yaml here in this PR and upload the updated feeds file?

2022-01-11 03:26 UTC, jjordan-quantum commented
Thanks Douglas,
I will branch from the main repo for prod where I need to duplicate this code.
I will update the feeds here and upload them with another commit to the upgraded PR.
Once the code is duplicated in the new branch for prod, I will update the yaml there as well

2022-01-13 18:11 UTC, merged